apiVersion: v1
kind: Service
metadata:
  name: film-program-service
  namespace: adrian
spec:
  selector:
    application: kino
    service: film-program
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 50000