apiVersion: v1
kind: Service
metadata:
  name: postgress
  namespace: adrian
spec:
  selector:
    application: database
    service: postgres
  type: ClusterIP
  ports:
    - port: 80
      nodePort: 5432