apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      type: aggregator
      service: elastic-search
  template:
    metadata:
      labels:
        type: aggregator
        service: elastic-search
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R g+rwX /usr/share/elasticsearch/data']
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-persistence
      containers:
        - name: elastic-search
          image: "elasticsearch:{{ .Values.elasticsearch.version }}"
          env:
            - name: "discovery.type"
              value: "single-node"
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-persistence
          resources:
            requests:
              memory: 1Gi
              cpu: "500m"
            limits:
              memory: 2Gi
              cpu: "1"
      volumes:
        - name: elastic-persistence
          persistentVolumeClaim:
            claimName: {{ .Values.elasticsearch.volume.name }}
