apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.elasticsearch.volume.name }}
  namespace: {{ .Values.namespace }}
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: {{ .Values.elasticsearch.volume.size }}