apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    type: aggregator
    service: elastic-search
  type: ClusterIP
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: 9200
      protocol: TCP