apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      type: ui
      service: kibana
  template:
    metadata:
      labels:
        type: ui
        service: kibana
    spec:
      containers:
        - name: kibana
          image: "kibana:{{ .Values.kibana.version }}"
          env:
            - name: "ELASTICSEARCH_HOSTS"
              value: "http://{{ .Values.elasticsearch.service.name}}.{{.Values.namespace}}:{{.Values.elasticsearch.service.port}}"
          ports:
            - containerPort: 5601

