apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admins-see-everything-role-binding
  namespace: adrian
subjects:
  - kind: User
    name: Adrian
  - kind: User
    name: Johannes
roleRef:
  apiGroup: "*"
  kind: Role
  name: admins-can-see-everything