apiVersion: v1
kind: Service
metadata:
  name: reservierungs-service
  namespace: adrian
spec:
  selector:
    application: kino
    service: reservierung
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 45000