apiVersion: v1
kind: Service
metadata:
  name: pg-admin-ui
  namespace: adrian
spec:
  selector:
    application: database
    service: pg-admin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
