apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: adrian
spec:
  selector:
    application: database
    service: postgres
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5432