apiVersion: v1
kind: Service
metadata:
  name: reservierung-service
  namespace: kino
  labels:
    app: tickets
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 45000
      protocol: TCP
  selector:
    app: reservierung