apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana_configs}}
  namespace: {{ .Values.namespace }}
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus.{{ .Values.namespace }}",
                "version": 1
            }
        ]
    }