apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    type: monitoring
    service: prometheus
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP