apiVersion: v1
kind: Service
metadata:
  name: film-program-service
  namespace: {{ .Release.Name }}
  labels:
    app: film-program
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 50000
      protocol: TCP
  selector:
    app: film-program