apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-program-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: film-program
spec:
  replicas: 3
  selector:
    matchLabels:
      app: film-program
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: film-program
    spec:
      containers:
        - name: film-program-container
          image: adrianmetzner/ci-kino-film-programm-service:1.0.0
          ports:
            - containerPort: 50000