apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "kino-ingress"
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: kino
spec:
  rules:
    - host: kino.{{ .Release.Name }}.sandbox.aws.wps.de
      http:
        paths:
          - path: /*
            backend:
              serviceName: "kino-service"
              servicePort: 80