apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: 504342896137.dkr.ecr.eu-central-1.amazonaws.com/ui:0.0.10
          env:
            - name: FILMPROGRAMM_SERVICE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: kino-config
                  key: film-program-service
            - name: RESERVIERUNGS_SERVICE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: kino-config
                  key: reservation-service
          ports:
            - containerPort: 80