apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: adrianmetzner/ci-kino-ui:1.1.0
          env:
            - name: FILMPROGRAMM_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: kino-config
                  key: film-program-service
            - name: RESERVIERUNGSSERVICE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: kino-config
                  key: reservation-service
          ports:
            - containerPort: 80