apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservierungs-service-pv-claim
  namespace: default
spec:
  storageClassName: slow
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce