apiVersion: v1
kind: Pod
metadata:
  name: reservierungs-service-pod
  namespace: adrian
spec:
  containers:
    - name: film-program
      image: adrianmetzner/ci-kino-reservierungs-service:1.1.0
      env:
        - name: FILMPROGRAMM_HOSTNAME
          value: 10.0.2.178:50000
      livenessProbe:
        httpGet:
          port: 45000
          path: /gesundheit/gesund
      ports:
        - containerPort: 45000
  restartPolicy: N
