apiVersion: v1
kind: Pod
metadata:
  name: web-ui-pod
  namespace: adrian
spec:
  containers:
    - name: film-program
      image: adrianmetzner/ci-kino-ui:1.1.0
      env:
        - name: FILMPROGRAMM_HOSTNAME
          value: 10-0-2-178.adrian.pod.cluster.local:50000
        - name: RESERVIERUNGSSERVICE_HOSTNAME
          value: 10-0-1-131.adrian.pod.cluster.local:45000
      livenessProbe:
        httpGet:
          port: 8081
      ports:
        - containerPort: 8081