apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservierungs-service-deployment
  namespace: adrian
  labels:
    application: kino
    service: reservierung
spec:
  selector:
    matchLabels:
      application: kino
      service: reservierung
  replicas: 3
  template:
    metadata:
      labels:
        application: kino
        service: reservierung
    spec:
      containers:
        - name: reservierungs-service
          image: adrianmetzner/ci-kino-reservierungs-service:1.2.6
          ports:
            - containerPort: 45000
          env:
            - name: FILMPROGRAMM_HOSTNAME
              value: film-program-service.adrian
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgress-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgress-secrets
          volumeMounts:
            - mountPath: /MicroReservierungsService/target/logs
              name: log-volume
            - mountPath: /MicroReservierungsService/target/properties
              name: postgres-props
              readOnly: true
      volumes:
        - name: log-volume
          hostPath:
            path: /var/logs
        - name: postgres-props
          configMap:
            name: reservierungs-db-config
            defaultMode: 0640

