apiVersion: v1
kind: Service
metadata:
  name: program-service
  labels:
    app: program
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 50000
      protocol: TCP
  selector:
    app: program