apiVersion: v1
kind: Secret
metadata:
  name: postgress-secrets
  namespace: adrian
type: Opaque
data:
  POSTGRES_PASSWORD: <base64 encoded password>
  POSTGRES_USER: <base64 encoded user>

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
  namespace: adrian
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: <base64 encoded password>
  PGADMIN_DEFAULT_EMAIL: <base64 encoded useremail>

