apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    type: ui
    service: kibana
  type: NodePort
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: 5601
      protocol: TCP