apiVersion: v1
kind: Service
metadata:
  name: kino-service
  namespace: kino
  labels:
    app: ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: ui